### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by StupidCodeFactory** [halogenandtoast/excelsior#2]
Parsing a simple (3, string fields).

ruby 1.8.7 (2009-12-24 patchlevel 248) [x86_64-linux], MBARI 0x6770, Ruby Enterprise Edition 2010.01

Linux blabla.local 2.6.32-24-server #43-Ubuntu SMP Thu Sep 16 16:05:42 UTC 2010 x86_64 GNU/Linux

**Comment by StupidCodeFactory** [comment]
Sorry, i forgot to add my issue: Basically i had a segmentation fault.

**Comment by halogenandtoast** [comment]
Thanks, I knew there were some segmentation faults, but I couldn't find them, can you provide an example of the csv file you were trying to parse?

**Comment by StupidCodeFactory** [comment]
Here it is:
locId,country,region,city,postalCode,latitude,longitude,metroCode,areaCode
301177,"IT","18","Fratticciola Selvatica","",43.1833,12.5333,,
301178,"FI","14","Pitkälänmäki","",63.3833,27.6167,,
301179,"CZ","90","Lipové","",49.2833,17.9167,,
301180,"BG","61","Istaccilar","",43.4333,27.9667,,
301181,"GB","Q5","Middlesmoor","",54.1667,-1.8500,,
301182,"NO","19","Fröisland","",58.0833,7.6667,,
301183,"RS","00","Golubac","",44.1914,20.0022,,
301184,"RS","00","Krnule","",44.5858,19.7536,,
301185,"GB","D4","Petertavy","",50.5667,-4.1000,,
301186,"CZ","30","Chotouchov","",49.9667,15.1333,,
301187,"FR","A3","Le Plessis-saint-benoit","",48.4333,2.0000,,
